import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'My Tonnes',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider appearance={{
      elements: {
        // Dark mode styling for Clerk components
        card: "bg-gray-800 shadow-xl border border-gray-700",
        formButtonPrimary: "bg-blue-600 hover:bg-blue-700 text-white",
        formFieldInput: "bg-gray-900 border-gray-700 text-white",
        formFieldLabel: "text-gray-300",
        footerActionLink: "text-blue-400 hover:text-blue-300",
        headerTitle: "text-white",
        headerSubtitle: "text-gray-400",
      }
    }}>
      <html lang="en" className="dark">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-gray-100`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              {/* <SignInButton /> */}
              {/* <SignUpButton /> */}
            </SignedOut>
            <SignedIn>
              {/* <UserButton /> */}
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}